/**
 * Prisma Seed Script for MedExpiry
 * Run via: npx tsx prisma/seed.ts
 */

import bcrypt from 'bcryptjs';

export const initialSeedData = {
  users: [
    {
      id: 'usr-admin-1',
      name: 'Dr. Sarah Jenkins (Chief Pharmacist)',
      email: 'admin@medexpiry.com',
      passwordHash: '$2a$10$wO3mYj0.6fE6n751YvV4sOWgV11MskPzO.rXm6e0r1k1s2b8.0/9a', // admin123
      role: 'ADMIN',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'usr-staff-1',
      name: 'Marcus Vance (Pharmacy Technician)',
      email: 'staff@medexpiry.com',
      passwordHash: '$2a$10$wO3mYj0.6fE6n751YvV4sOWgV11MskPzO.rXm6e0r1k1s2b8.0/9a', // staff123 (same hash for demo)
      role: 'STAFF',
      isActive: true,
      createdAt: '2026-01-15T09:30:00.000Z',
      updatedAt: '2026-01-15T09:30:00.000Z',
    },
  ],
  suppliers: [
    {
      id: 'sup-1',
      supplierName: 'PharmaCare Logistics Ltd.',
      contactPerson: 'David Ross',
      phone: '+1 (555) 234-5678',
      email: 'orders@pharmacare.example.com',
      address: '742 Evergreen Terrace, Sector 4, Springfield',
      licenseNumber: 'WDL-2024-8849',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'sup-2',
      supplierName: 'Apex Med Distribution',
      contactPerson: 'Elena Rostova',
      phone: '+1 (555) 345-6789',
      email: 'sales@apexmed.example.com',
      address: '100 Industrial Parkway, Suite 12, Metro City',
      licenseNumber: 'WDL-2023-7120',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'sup-3',
      supplierName: 'BioHealth Global Therapeutics',
      contactPerson: 'Dr. Tariq Al-Mansoor',
      phone: '+1 (555) 456-7890',
      email: 'tariq@biohealth.example.com',
      address: '45 Science Park Drive, Cambridge',
      licenseNumber: 'WDL-2025-9921',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'sup-4',
      supplierName: 'CureWell Pharmaceuticals',
      contactPerson: 'Mei-Ling Chen',
      phone: '+1 (555) 567-8901',
      email: 'contact@curewell.example.com',
      address: '88 Harbor Boulevard, Boston',
      licenseNumber: 'WDL-2022-6341',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'sup-5',
      supplierName: 'Lifeline Medical Supplies Co.',
      contactPerson: 'Arthur Pendelton',
      phone: '+1 (555) 678-9012',
      email: 'arthur@lifelinemed.example.com',
      address: '22 Elm Street, Minneapolis',
      licenseNumber: 'WDL-2025-4509',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  medicines: [
    {
      id: 'med-1',
      medicineName: 'Paracetamol 500mg',
      genericName: 'Acetaminophen',
      brandName: 'Panadol / Calpol',
      category: 'Analgesics & Antipyretics',
      dosageForm: 'Tablet',
      strength: '500 mg',
      manufacturer: 'GSK Consumer Healthcare',
      description: 'Used for mild-to-moderate pain and reduction of fever in adults and children.',
      minimumStockLevel: 50,
      createdAt: '2026-01-05T10:00:00.000Z',
      updatedAt: '2026-01-05T10:00:00.000Z',
    },
    {
      id: 'med-2',
      medicineName: 'Amoxicillin Clavulanate 625mg',
      genericName: 'Amoxicillin + Clavulanic Acid',
      brandName: 'Augmentin',
      category: 'Antibiotics',
      dosageForm: 'Tablet',
      strength: '500 mg / 125 mg',
      manufacturer: 'Sandoz Pharmaceuticals',
      description: 'Broad-spectrum beta-lactam antibacterial for respiratory, ENT, and skin infections.',
      minimumStockLevel: 30,
      createdAt: '2026-01-06T11:00:00.000Z',
      updatedAt: '2026-01-06T11:00:00.000Z',
    },
    {
      id: 'med-3',
      medicineName: 'Metformin Hydrochloride 500mg',
      genericName: 'Metformin HCl',
      brandName: 'Glucophage',
      category: 'Antidiabetics',
      dosageForm: 'Tablet',
      strength: '500 mg',
      manufacturer: 'Merck Healthcare',
      description: 'First-line biguanide anti-hyperglycemic oral medication for Type 2 diabetes mellitus.',
      minimumStockLevel: 40,
      createdAt: '2026-01-07T12:00:00.000Z',
      updatedAt: '2026-01-07T12:00:00.000Z',
    },
    {
      id: 'med-4',
      medicineName: 'Amlodipine Besylate 5mg',
      genericName: 'Amlodipine',
      brandName: 'Norvasc',
      category: 'Cardiovascular',
      dosageForm: 'Tablet',
      strength: '5 mg',
      manufacturer: 'Pfizer Inc.',
      description: 'Calcium channel blocker prescribed for hypertension and coronary artery disease.',
      minimumStockLevel: 35,
      createdAt: '2026-01-08T09:00:00.000Z',
      updatedAt: '2026-01-08T09:00:00.000Z',
    },
    {
      id: 'med-5',
      medicineName: 'Omeprazole 20mg Delayed-Release',
      genericName: 'Omeprazole',
      brandName: 'Prilosec',
      category: 'Gastrointestinal',
      dosageForm: 'Capsule',
      strength: '20 mg',
      manufacturer: 'AstraZeneca',
      description: 'Proton pump inhibitor (PPI) treating GERD, peptic ulcers, and acid reflux.',
      minimumStockLevel: 45,
      createdAt: '2026-01-09T14:00:00.000Z',
      updatedAt: '2026-01-09T14:00:00.000Z',
    },
    {
      id: 'med-6',
      medicineName: 'Azithromycin 500mg',
      genericName: 'Azithromycin',
      brandName: 'Zithromax',
      category: 'Antibiotics',
      dosageForm: 'Tablet',
      strength: '500 mg',
      manufacturer: 'Pfizer Inc.',
      description: 'Macrolide antibiotic active against various bacterial respiratory tract infections.',
      minimumStockLevel: 25,
      createdAt: '2026-01-10T15:00:00.000Z',
      updatedAt: '2026-01-10T15:00:00.000Z',
    },
    {
      id: 'med-7',
      medicineName: 'Cetirizine Hydrochloride 10mg',
      genericName: 'Cetirizine HCl',
      brandName: 'Zyrtec',
      category: 'Antihistamines',
      dosageForm: 'Tablet',
      strength: '10 mg',
      manufacturer: 'Johnson & Johnson',
      description: 'Second-generation non-sedating antihistamine for allergic rhinitis and chronic urticaria.',
      minimumStockLevel: 30,
      createdAt: '2026-01-11T10:30:00.000Z',
      updatedAt: '2026-01-11T10:30:00.000Z',
    },
    {
      id: 'med-8',
      medicineName: 'Salbutamol Inhaler 100mcg',
      genericName: 'Albuterol Sulfate',
      brandName: 'Ventolin HFA',
      category: 'Respiratory',
      dosageForm: 'Inhaler',
      strength: '100 mcg/dose',
      manufacturer: 'GSK Respiratory',
      description: 'Short-acting beta2-adrenergic bronchodilator for relief of acute bronchospasm in asthma.',
      minimumStockLevel: 20,
      createdAt: '2026-01-12T11:20:00.000Z',
      updatedAt: '2026-01-12T11:20:00.000Z',
    },
    {
      id: 'med-9',
      medicineName: 'Atorvastatin Calcium 20mg',
      genericName: 'Atorvastatin',
      brandName: 'Lipitor',
      category: 'Cardiovascular',
      dosageForm: 'Tablet',
      strength: '20 mg',
      manufacturer: 'Viatris Healthcare',
      description: 'HMG-CoA reductase inhibitor (statin) for hyperlipidemia and cardiovascular risk reduction.',
      minimumStockLevel: 40,
      createdAt: '2026-01-13T13:00:00.000Z',
      updatedAt: '2026-01-13T13:00:00.000Z',
    },
    {
      id: 'med-10',
      medicineName: 'Ciprofloxacin Eye/Ear Drops 0.3%',
      genericName: 'Ciprofloxacin',
      brandName: 'Ciloxan',
      category: 'Ophthalmic & Otic',
      dosageForm: 'Drops',
      strength: '0.3% w/v',
      manufacturer: 'Alcon Laboratories',
      description: 'Fluoroquinolone anti-infective topical drops for corneal ulcers and bacterial conjunctivitis.',
      minimumStockLevel: 15,
      createdAt: '2026-01-14T09:15:00.000Z',
      updatedAt: '2026-01-14T09:15:00.000Z',
    },
    {
      id: 'med-11',
      medicineName: 'Hydrocortisone Cream 1%',
      genericName: 'Hydrocortisone',
      brandName: 'Cortaid',
      category: 'Dermatological',
      dosageForm: 'Cream',
      strength: '1% w/w',
      manufacturer: 'Bayer Healthcare',
      description: 'Low-potency topical corticosteroid for dermatitis, eczema, and pruritus relief.',
      minimumStockLevel: 20,
      createdAt: '2026-01-15T16:00:00.000Z',
      updatedAt: '2026-01-15T16:00:00.000Z',
    },
    {
      id: 'med-12',
      medicineName: 'Ibuprofen Suspension 100mg/5ml',
      genericName: 'Ibuprofen',
      brandName: 'Advil Pediatric / Nurofen',
      category: 'Analgesics & Antipyretics',
      dosageForm: 'Syrup',
      strength: '100 mg / 5 ml',
      manufacturer: 'Reckitt Benckiser',
      description: 'Pediatric NSAID oral suspension for fever reduction and anti-inflammatory relief.',
      minimumStockLevel: 25,
      createdAt: '2026-01-16T11:45:00.000Z',
      updatedAt: '2026-01-16T11:45:00.000Z',
    },
    {
      id: 'med-13',
      medicineName: 'Insulin Glargine 100 IU/ml Solostar',
      genericName: 'Insulin Glargine',
      brandName: 'Lantus',
      category: 'Antidiabetics',
      dosageForm: 'Injection',
      strength: '100 IU / ml (3 ml)',
      manufacturer: 'Sanofi-Aventis',
      description: 'Long-acting basal human insulin analog indicated for glycemic control in diabetes.',
      minimumStockLevel: 15,
      createdAt: '2026-01-17T08:30:00.000Z',
      updatedAt: '2026-01-17T08:30:00.000Z',
    },
    {
      id: 'med-14',
      medicineName: 'Pantoprazole Injection 40mg',
      genericName: 'Pantoprazole Sodium',
      brandName: 'Protonix IV',
      category: 'Gastrointestinal',
      dosageForm: 'Injection',
      strength: '40 mg lyophilized vial',
      manufacturer: 'Sun Pharma',
      description: 'Intravenous PPI for short-term hospital management of acute upper GI bleed.',
      minimumStockLevel: 10,
      createdAt: '2026-01-18T10:00:00.000Z',
      updatedAt: '2026-01-18T10:00:00.000Z',
    },
  ],
};

export async function main() {
  console.log('Seed executed successfully.');
}

if (process.argv[1]?.includes('seed.ts')) {
  main().catch(console.error);
}
